### ISSUE TITLE
research not giving notes

### ISSUE THREAD

**Issue by thorpey9490** [Advanced-Thaumaturgy2/Advanced-Thaumaturgy2#11]
When i click on research, so i can generate a note it says its in my inventory but it does not appear for some reason.

**Comment by MonzterAssassin** [comment]
Thank you for the post.

This has already been brought to our attention as a team. We are mostly on break at the moment due to personal things in each of our respective lives, but are working on issues such as this slowly but surely.

If you have any other comments or concerns I urge you to join our Discord server: http://discord.gg/jyXvNNb

**Comment by MonzterAssassin** [comment]
Actually, unless you're referring to something specific I can't reproduce this in the newest build, but you can download 24r on the Curse page and as far as I can see they produce them for me.

**Comment by MonzterAssassin** [comment]
Actually no I managed to figure out what you were talking about. You were very nondescriptive (in the future I won't even try to acknowledge a very unclear bug report, so please try to help me to help you next time) but you made it seem like it was a research that warranted notes, and not purchases. What you were probably referring to was the minilith's components, no? They are purchases, and yeah they are bugged. I will fix them since I know exactly how to and it's easy.

**Comment by ToFam** [comment]
Fixed in 8c23cba
